# Generated by Django 4.2.5 on 2023-10-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedockerimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='basedockerimage',
            name='main_services_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='서비스 구분'),
        ),
        migrations.AlterField(
            model_name='basedockerimage',
            name='sub_services_name',
            field=models.CharField(blank=True, help_text='admin', max_length=200, null=True, verbose_name='부 서비스 구분'),
        ),
    ]
