# Generated by Django 4.2.5 on 2023-10-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_alter_basedockerimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDockerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dockerfile', models.TextField(blank=True, null=True, verbose_name='커멘드 명령어')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.basedockerimage', verbose_name='도커 이미지')),
            ],
        ),
    ]
