# Generated by Django 4.2.5 on 2023-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_docker', '0003_basedockerfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedockerfile',
            name='dockerfile_name',
            field=models.CharField(blank=True, default='Dockerfile.', max_length=200, null=True, verbose_name='도커파일 이름'),
        ),
    ]
