# Generated by Django 4.2.5 on 2023-10-02 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('builder_docker', '0005_remove_basedockerfile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockercomposeimage',
            name='name',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='프로젝트 이름'),
        ),
    ]
