# Generated by Django 4.2.5 on 2023-10-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_docker', '0006_alter_dockercomposeimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockercomposeimage',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='구분값'),
        ),
    ]
