# Generated by Django 4.2.5 on 2023-10-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_alter_dockercomposeimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedockerfile',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='이름'),
        ),
    ]
