name: Django CI & Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        cache: pip

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
        
    - name: Generate Environment Variables File for Production
      run: |
        echo "$VARIABLE" >> .env
      env:
        VARIABLE: ${{ secrets.VARIABLE }}

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Build coverage 
      run: |
        pytest --junitxml=/data/pytest.xml --cov-report=term-missing --cov docker_compose_gui tests/ | tee /data/pytest-coverage.txt
    
    - name: Pytest Coverage Comment
      if: ${{ github.ref == 'refs/heads/main' }}
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: /data/pytest-coverage.txt
        junitxml-path: /data/pytest.xml
        
    - name: Update Readme with Coverage Html
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

    - name: Commit & Push changes to Readme
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions-js/push@master
      with:
        message: Update coverage on Readme
        github_token: ${{ secrets.GITHUB_TOKEN }}
